export const TemplateForViews = [
  { name: "Template1", displayName: "Modern Layout" },
  { name: "Template2", displayName: "Minimalist Design" },
  { name: "Template3", displayName: "Corporate Theme" },
  { name: "Template4", displayName: "Creative Portfolio" },
  { name: "Template5", displayName: "Blog Layout" },
  { name: "Template6", displayName: "E-commerce" },
  { name: "Template7", displayName: "Landing Page" },
  { name: "Template8", displayName: "Dashboard" },
  { name: "Template9", displayName: "Magazine Style" },
  { name: "Template10", displayName: "Photography" },
  { name: "Template11", displayName: "Clubs Pro" },
  { name: "Template12", displayName: "Business Pro" },
  { name: "Template13", displayName: "Tech Startup" },
  { name: "Template14", displayName: "Agency" },
  { name: "Template15", displayName: "Restaurant" },
  { name: "Template16", displayName: "Fashion" },
  { name: "Template17", displayName: "Education" },
  { name: "Template18", displayName: "Healthcare" },
  { name: "Template19", displayName: "Real Estate" },
  { name: "Template20", displayName: "Music & Arts" },
];
